
`timescale 1ns / 1ps

`define APP_ID_WIDTH (2)
`define CORE_COUNT_WIDTH (6)
`define PRIORITY_WIDTH (2)

`define RL_DESC_WIDTH (128)

`define RL_DESC_LEN_SIZE (16)
`define RL_DESC_LEN_OF (0)

`define RL_DESC_CELL_ID_SIZE (16)
`define RL_DESC_CELL_ID_OF (16)
`define RL_DESC_APP_ID_SIZE (`APP_ID_WIDTH)
`define RL_DESC_APP_ID_OF (32)
`define RL_DESC_PRIO_SIZE (`PRIORITY_WIDTH)
`define RL_DESC_PRIO_OF (48)
`define RL_DESC_TS_SIZE (15)
`define RL_DESC_TS_OF (56)
`define RL_DESC_DROP_SIZE (1)
`define RL_DESC_DROP_OF (71)
`define RL_DESC_CSUM_SIZE (16)
`define RL_DESC_CSUM_OF (72)
`define RL_DESC_HASH_SIZE (32)
`define RL_DESC_HASH_OF (96)

`define RL_CELL_SIZE (1024)

// CPU MSG
`define CPU_MSG_WIDTH (32)
`define CPU_MSG_TYPE_SIZE (4)
`define CPU_MSG_TYPE_OF (0)
`define CPU_MSG_APP_ID_SIZE (`APP_ID_WIDTH)
`define CPU_MSG_APP_ID_OF (4)
`define CPU_MSG_APP_PRIO_SIZE (`PRIORITY_WIDTH)
`define CPU_MSG_APP_PRIO_OF (12)
`define CPU_MSG_APP_CONTENT_SIZE (16)
`define CPU_MSG_APP_CONTENT_OF (16)

// APP REGISTER FACTOR CONFIG
`define CPU_MSG_APP_BASE_FACTOR_SIZE (4)
`define CPU_MSG_APP_BASE_FACTOR_OF (16)
`define CPU_MSG_APP_PREE_FACTOR_SIZE (4)
`define CPU_MSG_APP_PREE_FACTOR_OF (20)


// APP config MSG
`define APP_MSG_WIDTH (`CPU_MSG_WIDTH)
`define APP_MSG_TYPE_SIZE (4)
`define APP_MSG_TYPE_OF (0)
`define APP_MSG_APP_ID_SIZE (`APP_ID_WIDTH)
`define APP_MSG_APP_ID_OF (4)
`define APP_MSG_APP_PRIO_SIZE (`PRIORITY_WIDTH)
`define APP_MSG_APP_PRIO_OF (12)
`define APP_MSG_APP_PORT_SIZE (16)
`define APP_MSG_APP_PORT_OF (16)

// alter app msg for different type
`define APP_MSG_APP_SCALE_DOWN_EPOCH_SIZE (6)
`define APP_MSG_APP_SCALE_DOWN_EPOCH_OF (12)
`define APP_MSG_APP_CONG_EPOCH_SIZE (6)
`define APP_MSG_APP_CONG_EPOCH_OF (20)
`define APP_MSG_APP_SCALE_DOWN_THRESH_SIZE (4)
`define APP_MSG_APP_SCALE_DOWN_THRESH_OF (28)

// CPU MSG TYPE
`define CPU_MSG_ENABLE_QUEUE (1)
`define CPU_MSG_DISABLE_QUEUE (2)
`define CPU_MSG_ACTIVATE_APP_THREAD (3)
`define CPU_MSG_DEACTIVATE_APP_THREAD (4)
`define CPU_MSG_FEEDBACK_THREAD (5)
`define CPU_MSG_ARM_CONG_MONITOR (6)
`define CPU_MSG_ARM_SCALE_DOWN_MONITOR (7)

// APP MSG TYPE
`define APP_MSG_CONIFG_APP (0)
`define APP_MSG_CONFIG_MONITOR (1)
`define APP_MSG_RESET_MONITOR (2)


// NIC-CPU hint
`define NIC_MSG_WIDTH (32)
`define NIC_MSG_TYPE_SIZE (4)
`define NIC_MSG_TYPE_OF (0)
`define NIC_MSG_APP_ID_SIZE (`APP_ID_WIDTH)
`define NIC_MSG_APP_ID_OF (4)
`define NIC_MSG_CONTENT_SIZE (16)
`define NIC_MSG_CONTENT_OF (16)

// NIC MSG TYPE
`define NIC_MSG_SCALE_DOWN_HINT (1)
`define NIC_MSG_CONG_HINT (2)
